// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var canvas, main;
    window.Canvas = Canvas;
    window.Cell = Cell;
    canvas = new Canvas('c');
    main = function() {
      return canvas.nextStep();
    };
    return setInterval(main, 100);
  });

}).call(this);
